format_version: 10
pipelines:
  pipeline-yaml:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-b3c1816:
        git: https://github.com/praveen6370/go-cd.git
        shallow_clone: false
        auto_update: true
        branch: yaml
    stages:
    - stage-yaml:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job-yaml:
            timeout: 0
            environment_variables:
              a: s
              s: sd
            secure_variables:
              AWS_SECRET_ACCESS_KEY: AES:yw48IPDJj9KJfBn6CA8o0w==:c3TuE9D5rHC0lk9k2pfRIA0tCmU0UE28YcWOV62Vjxz9GW2sHgh6lTtBpduOj6nc
              AWS_ACCESS_KEY_ID: AES:hLKz3ktT9bBxjmu75vnJrw==:TAvlx/O+ELcTDbV6ECp3l5BjeSKhiRWvE2/i34gdRvI=
            tasks:
            - exec:
                arguments:
                - configure
                - set
                - secret_key=$AWS_SECRET_ACCESS_KEY
                - access_key=$AWS_ACCESS_KEY_ID
                command: aws
                run_if: passed
            - exec:
                arguments:
                - s3
                - ls
                command: aws
                run_if: passed
    - stage2-yaml:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job2-yaml:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - /var/go/.aws
                command: cd
                run_if: passed
            - exec:
                arguments:
                - config
                command: rm
                run_if: passed
            - exec:
                command: pwd
                run_if: passed